# Generated by Django 4.0.7 on 2022-10-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailsearch", "0006_customise_indexentry"),
    ]

    operations = []
