# Generated by Django 5.2.5 on 2025-09-03 19:45

import uuid
import wagtailsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtests', '0003_book_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertWithCustomUUIDPrimaryKey',
            fields=[
                ('advert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            bases=(wagtailsearch.index.Indexed, models.Model),
        ),
    ]
