# Generated by Django 5.2.5 on 2025-09-04 16:52

import wagtailsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtests', '0004_advertwithcustomuuidprimarykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(wagtailsearch.index.Indexed, models.Model),
        ),
    ]
